#!/bin/bash

docker run -d --name excel2csv-container -v $(pwd)/data:/data sae103-excel2csv tail -f /dev/null
docker cp ./'Tableau des medailles v2'.xlsx excel2csv-container:/data
docker exec excel2csv-container ssconvert /data/'Tableau des medailles v2'.xlsx resultat.csv
docker cp excel2csv-container:/data/resultat.csv resultat.csv

# Vérifier si la conversion a réussi et afficher un message
if [ -f "resultat.csv" ]; then
  echo "Conversion réussie : test.xlsx -> resultat.csv"
else
  echo "Erreur lors de la conversion."
fi

docker rm -f excel2csv-container



#commande de tri des medailles 